// <auto-generated />
using EZCom.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EZCom.Migrations
{
    [DbContext(typeof(EZComDbContext))]
    [Migration("20250625043544_Initial DB and Product Table Creation")]
    partial class InitialDBandProductTableCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EZCom.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop with 16GB RAM and 512GB SSD.",
                            ImageFileName = "laptop.jpg",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latest smartphone with 128GB storage and 12MP camera.",
                            ImageFileName = "smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise-cancelling over-ear headphones with Bluetooth connectivity.",
                            ImageFileName = "headphones.jpg",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stylish smartwatch with fitness tracking and heart rate monitor.",
                            ImageFileName = "smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "10-inch tablet with high-resolution display and long battery life.",
                            ImageFileName = "tablet.jpg",
                            Name = "Tablet",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ergonomic wireless mouse with adjustable DPI settings.",
                            ImageFileName = "wireless_mouse.jpg",
                            Name = "Wireless Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Portable Bluetooth speaker with deep bass and long battery life.",
                            ImageFileName = "bluetooth_speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "1TB external hard drive for secure data storage.",
                            ImageFileName = "external_hard_drive.jpg",
                            Name = "External Hard Drive",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mechanical gaming keyboard with customizable RGB lighting.",
                            ImageFileName = "gaming_keyboard.jpg",
                            Name = "Gaming Keyboard",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "27-inch 4K monitor with ultra-thin bezels and HDR support.",
                            ImageFileName = "4k_monitor.jpg",
                            Name = "4K Monitor",
                            Price = 499.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
